### ISSUE TITLE
When clicking on employee / candidate button on PIM menu and updating profile

### ISSUE THREAD

**Issue by jhunchua** [adevait/hrm#2]
1. Employee:
FatalErrorException in EmployeesController.php line 49:
syntax error, unexpected '::' (T_PAAMAYIM_NEKUDOTAYIM), expecting ']'
in EmployeesController.php line 49

2. Candidates
in CandidatesController.php line 38
FatalErrorException in CandidatesController.php line 38:
syntax error, unexpected '::' (T_PAAMAYIM_NEKUDOTAYIM), expecting ']'
in CandidatesController.php line 38

3. Updating profile:
FatalErrorException in EmployeeRepository.php line 22:
syntax error, unexpected '::' (T_PAAMAYIM_NEKUDOTAYIM)
in EmployeeRepository.php line 22

**Comment by trajchevska** [comment]
One of the requirements for the system to work properly is a PHP version >= 5.6.4 (see [Laravel's documentation](https://laravel.com/docs/5.3) for reference). The issue you're facing here is because your PHP version doesn't allow dynamically accessing the class constants, i.e. `$this->employeeRepository->model::USER_ROLE_EMPLOYEE`.
